spring:
  jackson:
    default-property-inclusion: NON_NULL
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: v
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8092
management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'flyway']
